### PR TITLE
CCF_AS_CT.owl extension

### LINKED ISSUE #143: A proposed extension to CCF_AS_CT.owl
STATUS: Draft.  Discussion required prior to implementation.

In cases where tables do not validate well, CCF_AS_CT.owl can have too few relationships to be useful.  Even in cases that do validate, some terms may float free from the graph, even if they are well connected in Uberon & CL. The proposal aims to take advantage of that connectedness.

Proposal:
For every orphan term (one with no existential restrictions), find all relationships by permitted relation types in the redundant graph to other terms the table.  Then use standard redundancy stripping (robot reduce) to remove any redundancy.   (I'm not sure of the best way to find orphan terms)

Note:  we need to ensure CCF.owl has fully axiomatised RO object properties for this to work - but we should make sure of that anyway.

### PR DESCRIPTION
**Pull request by anitacaron**
Fixes #143

I merged the new relationships to graph to have a better view with the not validated relationships. Do I create another graph file with both validated and new relationshiops and without the not validated relationships?

The `{organ}_extended.owl` is the merged valid and the new relationships after remove any redundancy (robot reduce).

### CODE REVIEW

**Comment by dosumis** [comment]
Issues:

1. Redundancy is not being stripped.  Pulling in relation axiomatization from RO needed.
2. Strip back to the relations specified here: https://github.com/hubmapconsortium/ccf-validation-tools/issues/143#issuecomment-1054094951 (we don't need part_of)

**Comment by anitacaron** [comment]
For 3: I didn't find anything to show different colours for the same property in og2dot.

**Comment by dosumis** [comment]
> For 3: I didn't find anything to show different colours for the same property in og2dot. I'll remove the new links from graphs.

Looks like might be possible by hacking JSON like this:

image

https://www.npmjs.com/package/obographviz

@cmungall - is there also a default for rendering inferred edges we could hack?

**Review by dosumis — APPROVED** [review]
Looks good.  Please make a new ticket and separate PR for updates to graphs to show newly added relationships from Uberon/CL

**Comment by cmungall** [comment]
Not sure if you still need my help, renderd graphs look great, and including the kgviz property directly is probably your best bet.

I would like to decouple this and have a standard way of saying an axiom is inferred

See:

 - https://github.com/information-artifact-ontology/ontology-metadata/issues/95

**Pull request merged**
